# Generated by Django 2.0.6 on 2019-08-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='editing',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='done',
            field=models.TextField(default=0),
        ),
    ]
