# Generated by Django 2.0.6 on 2019-08-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190818_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='editing',
        ),
        migrations.AlterField(
            model_name='note',
            name='done',
            field=models.BooleanField(default=0),
        ),
    ]
