# Generated by Django 2.0.6 on 2019-08-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190818_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='editing',
            field=models.BooleanField(default=0),
        ),
    ]
