# Generated by Django 2.0.6 on 2019-08-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_desk_table_tablenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
