# Generated by Django 2.0.6 on 2019-08-21 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_note_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='color',
        ),
    ]
