# Generated by Django 2.0.6 on 2019-08-22 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_table_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablenote',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Table'),
        ),
    ]
